const models = [
  {
    modelName: 'PHPDM1',
    data: ['Hearing aid usage', 'Hearing aid satisfaction'],
    factors: [
      'Environment',
      'Outdoor Activities',
      'Location',
      'Education',
      'Significant Others',
      'Age',
      'Gender',
      'Personal Care',
      'Civil Status',
      'Smoking',
      'Diabetes',
      'Obesity',
      'Ototoxicity',
      'Cause',
      'Heart Rate',
      'Respiratory Rate',
      'MOCA',
      'Reaction Time',
      'Forward Digit Recall',
      'Reverse Digit Recall',
      'HADS',
      'Occupation',
      'Employment',
    ],
  },
  {
    modelName: 'PHPDM2',
    data: [
      'Noise Induced Hearing Loss (NIHL)',
      'Occupational Noise',
      'Social Noise',
      'Permanent Threshold Shift (PTS)',
      'Temporary Threshold Shift (TTS)',
      'Sound Pressure Level',
    ],
    factors: ['Pure Tone Audiometry', 'Hearing Aid Usage'],
  },
  {
    modelName: 'PHPDM3',
    data: ['GHABP', 'Hearing Aid Use', 'MOCA', 'Listening Effort'],
    factors: [
      'Auditory Training Type',
      'Auditory Training Dosage',
      'Education',
    ],
  },
  {
    modelName: 'PHPDM4',
    data: ['MOCA', 'HUI3', 'Hearing aid usage'],
    factors: [
      'Diabetes',
      'Smoking',
      'Vascular disease',
      'Dementia',
      'Occupation',
      'Education',
      'Age',
      'Reading Span',
      'Verbal reaction time',
      'Mood monitoring',
      'Reverse digit Recall',
      'HADS',
      'Social Engagement',
    ],
  },
];

export default models;
